import os

netlist_content = """(export (version D)
  (components
    (comp (ref J1)
      (value ESP32_Left)
      (footprint Connector_PinHeader_2.54mm:PinHeader_1x18_P2.54mm_Vertical)
    )
    (comp (ref J2)
      (value ESP32_Right)
      (footprint Connector_PinHeader_2.54mm:PinHeader_1x18_P2.54mm_Vertical)
    )
    (comp (ref J3)
      (value Relay)
      (footprint Connector_PinHeader_2.54mm:PinHeader_1x03_P2.54mm_Vertical)
    )
    (comp (ref J4)
      (value PiBridge)
      (footprint Connector_PinHeader_2.54mm:PinHeader_1x04_P2.54mm_Vertical)
    )
    (comp (ref J5)
      (value Tamper1)
      (footprint Connector_PinHeader_2.54mm:PinHeader_1x02_P2.54mm_Vertical)
    )
    (comp (ref J6)
      (value Tamper2)
      (footprint Connector_PinHeader_2.54mm:PinHeader_1x02_P2.54mm_Vertical)
    )
  )
  (nets
    (net (code 1) (name 5V)
      (node (ref J1) (pin 1))
      (node (ref J3) (pin 1))
      (node (ref J4) (pin 1))
    )
    (net (code 2) (name GND)
      (node (ref J1) (pin 2))
      (node (ref J3) (pin 2))
      (node (ref J4) (pin 2))
      (node (ref J5) (pin 2))
      (node (ref J6) (pin 2))
    )
    (net (code 3) (name ESP_RX)
      (node (ref J2) (pin 16))
      (node (ref J4) (pin 3))
    )
    (net (code 4) (name ESP_TX)
      (node (ref J2) (pin 17))
      (node (ref J4) (pin 4))
    )
    (net (code 5) (name RELAY_IN)
      (node (ref J2) (pin 4))
      (node (ref J3) (pin 3))
    )
    (net (code 6) (name TAMPER1)
      (node (ref J2) (pin 5))
      (node (ref J5) (pin 1))
    )
    (net (code 7) (name TAMPER2)
      (node (ref J2) (pin 6))
      (node (ref J6) (pin 1))
    )
  )
)
"""

file_path = r"C:\Users\prajw\.openclaw\blackbox-sentinel\Sentinel_Carrier\Sentinel_Carrier.net"
with open(file_path, "w") as f:
    f.write(netlist_content)
print(f"Netlist created successfully at {file_path}")
