import os
import sys
import time
import json
import base64
import tempfile
import subprocess
import shutil
from pathlib import Path
from datetime import datetime, timezone
from dataclasses import dataclass
from typing import Optional, Tuple, Dict, Any

try:
    from PIL import Image, ImageGrab
except ImportError:
    Image = None

try:
    import google.generativeai as genai
except ImportError:
    genai = None

# Ensure we can import our M3 ledger and contracts
PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
sys.path.insert(0, os.path.join(PROJECT_ROOT, "m3-ml-ledger", "src"))
sys.path.insert(0, os.path.join(PROJECT_ROOT, "common"))

from ledger import HashChainLedger
from m3_security_contracts import ContainmentReceiptService, Ed25519ReceiptSigner, SoftwareMonotonicCounter

@dataclass
class DiagnosticContext:
    framebuffer_image_path: Optional[str]
    system_logs: str
    thermal_data: str
    target_script: str

class SelfHealingOrchestrator:
    """
    Autonomous Self-Healing Agent.
    Implements:
    1. VLM Framebuffer scraping
    2. Zero-cost thermal diagnostics
    3. Ephemeral Sandboxing
    4. Quorum-Based Healing (LLM-as-a-Judge)
    5. Immutable Audit Trail (Ed25519)
    """
    
    SYSTEM_PROMPT = """You are an elite, autonomous, bare-metal diagnostic and self-healing agent for the BlackBox Sentinel edge security node.
Your sole purpose is to analyze failing Python scripts or system states, identify the root cause, and output a perfect, drop-in replacement script that fixes the issue.

### INSTRUCTIONS:
1. You will receive a diagnostic context containing:
   - A screenshot or framebuffer capture of the physical display.
   - The last 50 lines of system or application logs.
   - Hardware thermal data.
   - The raw source code of the failing target script.
2. Analyze ALL context systematically. Think step-by-step internally:
   - Step A: Does the screenshot show a kernel panic, a frozen GUI, or an error dialog?
   - Step B: Do the logs show a stack trace or an unexpected exception?
   - Step C: Is the CPU thermally throttling (>85°C)? 
   - Step D: Correlate these signals to locate the exact lines in the target script causing the failure.
3. Formulate a highly robust, secure, and performant patch.
4. **CRITICAL OUTPUT FORMAT:** You must output exactly ONE markdown code block containing the ENTIRE updated Python file. Do NOT truncate. Do NOT output partial diffs. Output the full, complete, patched code. 
5. Do NOT include markdown explanations, apologies, or pleasantries outside the code block. Your output must begin with ```python and end with ```.

### SECURITY & SAFETY RULES:
- Do NOT bypass or remove existing cryptographic boundaries (e.g., ContainmentReceiptService).
- Do NOT hardcode private keys.
- Ensure all loops have proper non-blocking sleeps.
- Maintain all existing GUI aesthetic configurations.
"""

    QUORUM_PROMPT = """You are the Quorum Auditor AI. You are a secondary validation agent.
You are reviewing a proposed code patch generated by another AI to fix a failing system.
Review the code for:
1. Syntax errors.
2. Malicious behaviors (backdoors, data exfiltration).
3. Logic regressions (removing security checks).
If the patch is SAFE and CORRECT, output exactly the word "APPROVED".
If the patch is DANGEROUS or BROKEN, output exactly the word "REJECTED" followed by a 1-sentence reason.
"""

    def __init__(self, target_script: str):
        self.target_script = os.path.abspath(target_script)
        self.node_id = "AEDN-HEALER-01"
        
        # Initialize Gemini API
        api_key = os.environ.get("GEMINI_API_KEY")
        if not api_key:
            raise ValueError("GEMINI_API_KEY environment variable is required.")
        genai.configure(api_key=api_key)
        
        # We use Gemini Pro or Flash. The user stated they have Gemini Pro.
        self.model = genai.GenerativeModel('gemini-3.5-flash')
        self.quorum_model = genai.GenerativeModel('gemini-3.5-flash') # Fast model for double-check
        
        # Initialize Cryptography and Ledger
        self.ledger_path = os.path.join(PROJECT_ROOT, "m3-ml-ledger", "data", "healing_ledger.json")
        counter_path = os.path.join(PROJECT_ROOT, "m3-ml-ledger", "data", "healing_counter.txt")
        self.ledger = HashChainLedger(self.ledger_path)
        self.counter = SoftwareMonotonicCounter(counter_path)
        
        priv_key_b64 = os.environ.get("SENTINEL_ED25519_KEY")
        if priv_key_b64:
            self.signer = Ed25519ReceiptSigner.from_private_bytes(base64.urlsafe_b64decode(priv_key_b64))
        else:
            self.signer = Ed25519ReceiptSigner() # Ephemeral for simulation
            
        self.receipt_service = ContainmentReceiptService(self.ledger, self.counter, self.signer, self.node_id)
        
    def _gather_thermal(self) -> str:
        """Zero-cost thermal reading using internal CPU sensor."""
        try:
            with open("/sys/class/thermal/thermal_zone0/temp", "r") as f:
                temp_c = int(f.read().strip()) / 1000.0
                return f"CPU Temperature: {temp_c:.1f}°C"
        except FileNotFoundError:
            # Fallback for Windows/Mac dev environments
            return "CPU Temperature: 45.0°C (Simulated)"

    def _gather_framebuffer(self) -> Optional[str]:
        """Capture the screen or framebuffer."""
        tmp_img = os.path.join(tempfile.gettempdir(), "fb_capture.png")
        if sys.platform == "linux" and os.path.exists("/dev/fb0"):
            # Mocking actual fb0 read here, normally requires struct unpacking RGB565.
            # We'll use Pillow's ImageGrab as a universal fallback if running in X11
            pass
            
        if Image and hasattr(ImageGrab, "grab"):
            try:
                img = ImageGrab.grab()
                img.save(tmp_img, "PNG")
                return tmp_img
            except Exception:
                pass
        return None

    def _gather_logs(self) -> str:
        # Dummy log gathering. In production, `tail -n 50 /var/log/syslog`
        return "[SYSTEM] Agent started.\n[ERROR] Exception in worker thread: ZeroDivisionError"

    def _run_sandbox_test(self, patched_code: str) -> Tuple[bool, str]:
        """Ephemeral RAM-Disk Sandboxing."""
        # On Linux, /dev/shm is a tmpfs (RAM disk). On Windows, use tempfile.
        shm_dir = "/dev/shm" if os.path.exists("/dev/shm") else tempfile.gettempdir()
        sandbox_dir = os.path.join(shm_dir, f"sentinel_sandbox_{int(time.time())}")
        os.makedirs(sandbox_dir, exist_ok=True)
        
        test_file = os.path.join(sandbox_dir, "patched_test.py")
        try:
            with open(test_file, "w", encoding="utf-8") as f:
                f.write(patched_code)
                
            # Compile to check syntax
            result = subprocess.run([sys.executable, "-m", "py_compile", test_file], capture_output=True, text=True)
            if result.returncode != 0:
                return False, result.stderr
            return True, "Syntax Check Passed."
        finally:
            # Ephemeral: always evaporates
            shutil.rmtree(sandbox_dir, ignore_errors=True)

    def _quorum_check(self, patched_code: str) -> bool:
        """Quorum-Based Healing: The second LLM call verifies the first."""
        prompt = self.QUORUM_PROMPT + "\n\n### PROPOSED PATCH:\n```python\n" + patched_code + "\n```"
        try:
            response = self.quorum_model.generate_content(prompt)
            decision = response.text.strip().split("\n")[0]
            if decision.startswith("APPROVED"):
                return True
            print(f"[QUORUM] Rejected: {response.text}")
            return False
        except Exception as e:
            print(f"[QUORUM] Error calling quorum model: {e}")
            return False

    def heal(self):
        print("[ORCHESTRATOR] Initiating Self-Healing sequence...")
        
        # 1. Gather context
        thermal = self._gather_thermal()
        logs = self._gather_logs()
        fb_img_path = self._gather_framebuffer()
        
        try:
            with open(self.target_script, "r", encoding="utf-8") as f:
                source_code = f.read()
        except FileNotFoundError:
            print(f"[ORCHESTRATOR] Error: Target script {self.target_script} not found.")
            return

        print("[ORCHESTRATOR] Context gathered. Querying VLM for patch...")
        
        # 2. Build Multimodal Prompt
        prompt_parts = [
            self.SYSTEM_PROMPT,
            "\n### THERMAL DATA:\n" + thermal,
            "\n### SYSTEM LOGS:\n" + logs,
            "\n### TARGET SCRIPT SOURCE:\n```python\n" + source_code + "\n```"
        ]
        
        if fb_img_path and Image:
            try:
                img = Image.open(fb_img_path)
                prompt_parts.append(img)
            except Exception:
                pass
                
        # 3. Generate Patch
        try:
            response = self.model.generate_content(prompt_parts)
        except Exception as e:
            print(f"[ORCHESTRATOR] Failed to call Gemini API: {e}")
            return
            
        text = response.text
        if "```python" not in text:
            print("[ORCHESTRATOR] Agent failed to return a python code block.")
            return
            
        patched_code = text.split("```python")[1].split("```")[0].strip()
        
        print("[ORCHESTRATOR] Patch generated. Running Sandboxed testing...")
        
        # 4. Ephemeral Sandbox Test
        passed, msg = self._run_sandbox_test(patched_code)
        if not passed:
            print(f"[ORCHESTRATOR] Sandbox validation FAILED: {msg}")
            return
            
        print("[ORCHESTRATOR] Sandbox passed. Executing Quorum validation...")
        
        # 5. Quorum Validation
        if not self._quorum_check(patched_code):
            print("[ORCHESTRATOR] Quorum validation FAILED. Patch aborted.")
            return
            
        print("[ORCHESTRATOR] Quorum APPROVED. Cryptographically signing patch...")
        
        # 6. Cryptographic Ledger Logging
        # We reuse the ContainmentReceiptService to issue a 'HEAL' event instead of 'CONTAIN'
        ts = int(time.time())
        incident_id = f"{self.node_id}:heal:{ts}"
        
        event = self.ledger.add_entry("self_healing_patch", {
            "organization_id": "openclaw-sentinel",
            "incident_id": incident_id,
            "target_file": os.path.basename(self.target_script),
            "quorum_status": "APPROVED",
            "controller_id": self.node_id
        })
        
        # In a full integration, we'd generate a real Ed25519 receipt and transmit it via UART.
        print(f"[ORCHESTRATOR] Patch recorded to Immutable Ledger. Hash: {event['hash']}")
        
        # 7. Apply Patch
        backup_path = self.target_script + f".backup_{ts}"
        shutil.copy2(self.target_script, backup_path)
        with open(self.target_script, "w", encoding="utf-8") as f:
            f.write(patched_code)
            
        print("[ORCHESTRATOR] Fix successfully deployed! File replaced.")
        print("[ORCHESTRATOR] Sending OOB Notification (Mock SMS)...")
        # Self-healing SMS notification
        try:
            from hal import get_hal
            h = get_hal(mode="sim", node_id=self.node_id)
            h.cellular.send_sms("+919876543210", f"AI HEALED: {os.path.basename(self.target_script)} patched. Hash: {event['hash'][:8]}")
        except Exception:
            pass
            
if __name__ == "__main__":
    if len(sys.argv) > 1:
        target = sys.argv[1]
    else:
        # Default test target
        target = os.path.join(PROJECT_ROOT, "scratch", "broken_script.py")
        os.makedirs(os.path.dirname(target), exist_ok=True)
        with open(target, "w", encoding="utf-8") as f:
            f.write("def do_work():\n    return 1 / 0\n")
            
    healer = SelfHealingOrchestrator(target)
    healer.heal()
